Trying to fix jinja2 import error
When pushing to prod I'm getting the following error:

```
ImportError: cannot import name 'escape' from 'jinja2'
```

It looks like some library I'm using is importing something from Jinja2
which has been deprecated and removed. Fixing the version of `Jinja2` to
`3.0.3` should fix this issue
according to: https://github.com/pallets/jinja/issues/1626